[package]
name = "oxineat"
version = "0.2.1"
authors = ["Fr4ctlize <fortizk@outlook.com>"]
edition = "2018"
license = "MIT"
description = "A Rust implementation of NeuroEvolution of Augmenting Topologies"
repository = "https://github.com/Fr4ctlize/OxiNEAT"
documentation = "https://docs.rs/oxineat/"
readme = "README.md"
keywords = ["neat", "neuroevolution"]

[dependencies]
rand = "0.8.3"
serde = { version = "1.0.129", features = ["derive"] }
ahash = "0.7.4"

[dev-dependencies]
oxineat-nn = { path = "../oxineat-nn" }